version: "3.3"
services:
  api:
    image: golang:1.23-alpine
    container_name: unicorn-api
    working_dir: /app
    volumes:
      - ./:/app
      - /var/www/unicorn/uploads:/uploads
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: ["sh","-c","go mod tidy && go mod download && go build -o /tmp/app ./cmd/server && /tmp/app"]
    restart: unless-stopped
